### ISSUE TITLE
투표 기능 제작

### ISSUE THREAD

**Issue by JwaJungwoo** [ProjectInTheClass/Calendar-Vot#1]
발신자
->
0. 투표 이름 입력
1. (날짜 + 시간) 선택, 불참 선택지 Default로 추가
2. 장소 선택(일단은 텍스트)
3. 발신

+@. 옵션 (복수 선택, 선택지 추가, 익명 투표, 마감 기한 설정)

수신자
->
0. 투표 수신
1. 투표
2. 발신
3. 실시간 종합 Update

**Comment by yhr7518** [comment]
문제점:
1. 투표 결과가 동점일 때 어느 것을 선택할것인가
2. iMessage app에서는 push notification이 불가능한데, 투표가 종료된 것과 투표 결과를 어떻게 알릴지?
3. 사용자 캘린더에 알림 없이 바로 추가할지?
