### ISSUE TITLE
UI 설계

### ISSUE THREAD

**Issue by JwaJungwoo** [ProjectInTheClass/Calendar-Vot#2]
UI 설계 및 배치 (Calendar앱 및 Vyte앱 UI 참고)

**Comment by yhr7518** [comment]
AddView Scene(새로운 투표를 추가할 때 나오는 씬)의 레이아웃을 구성

2642ec00eafaa609aa88edd043dd74131d2449b9

**Comment by yhr7518** [comment]
![2016-11-24 3 25 36](https://cloud.githubusercontent.com/assets/18374532/20588675/4ca780d2-b25a-11e6-976f-4b77e2e83cac.png)

Add Vote Scene 레이아웃 구성 및 기능 구현 (옵션 제외)
